#!/usr/bin/env bash
# vLLM Manager — node onboarding.
#
# Run this on a NEW box to join it to an existing cluster. Get the one-liner
# (with a join token) from the admin UI:
#
#   curl -sfL http://<admin>:7080/join.sh | sudo bash -s -- --token <TOKEN> --admin-url http://<admin>:7080
#
# It clones the repo (for run.sh), pulls the cluster's image, writes a minimal
# .env and starts the node agent. Everything else — GPUs, RDMA HCA/GID, NICs,
# volumes — the agent detects and reports for itself.
set -euo pipefail

TOKEN="" ADMIN_URL="" ROLES="participant" MODELS_DIR="/export/llm_models"
INSTALL_DIR="/opt/vllm-manager" REPO="https://github.com/inchix/vllm_manager.git"
IMAGE_REF="" CLUSTER_ID="default" BRANCH="main"

while [ $# -gt 0 ]; do case "$1" in
  --token) TOKEN="$2"; shift 2;;
  --admin-url) ADMIN_URL="$2"; shift 2;;
  --roles) ROLES="$2"; shift 2;;
  --models-dir) MODELS_DIR="$2"; shift 2;;
  --install-dir) INSTALL_DIR="$2"; shift 2;;
  --image) IMAGE_REF="$2"; shift 2;;
  --cluster-id) CLUSTER_ID="$2"; shift 2;;
  --branch) BRANCH="$2"; shift 2;;
  --repo) REPO="$2"; shift 2;;
  -h|--help) sed -n '2,12p' "$0"; exit 0;;
  *) echo "unknown arg: $1" >&2; exit 1;;
esac; done

[ -n "$TOKEN" ] || { echo "ERROR: --token is required (mint one in the admin UI)" >&2; exit 1; }
[ -n "$ADMIN_URL" ] || { echo "ERROR: --admin-url is required" >&2; exit 1; }

say() { printf '\n== %s\n' "$*"; }

say "Checking prerequisites"
RUNTIME=""
for r in podman docker; do command -v "$r" >/dev/null 2>&1 && { RUNTIME="$r"; break; }; done
[ -n "$RUNTIME" ] || { echo "ERROR: need podman or docker installed" >&2; exit 1; }
command -v git >/dev/null 2>&1 || { echo "ERROR: git is required" >&2; exit 1; }
echo "  runtime: $RUNTIME"
if [ -e /dev/nvidiactl ] || command -v nvidia-smi >/dev/null 2>&1; then
  echo "  NVIDIA driver: present"
else
  echo "  WARNING: no NVIDIA driver detected — this node will join with 0 GPUs"
fi
[ -d /sys/class/infiniband ] && echo "  RDMA: $(ls /sys/class/infiniband 2>/dev/null | tr '\n' ' ')" \
                             || echo "  RDMA: none detected (TCP fallback)"

say "Fetching the repo into $INSTALL_DIR"
if [ -d "$INSTALL_DIR/.git" ]; then
  git -C "$INSTALL_DIR" fetch --depth 1 origin "$BRANCH" && git -C "$INSTALL_DIR" reset --hard FETCH_HEAD
else
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone --depth 1 --branch "$BRANCH" "$REPO" "$INSTALL_DIR"
fi

say "Obtaining the cluster image"
# The whole cluster must run a byte-identical image, so we PULL the one the
# cluster was built with rather than building locally. The admin advertises it.
if [ -z "$IMAGE_REF" ]; then
  IMAGE_REF="$(curl -sfL "$ADMIN_URL/api/cluster/image" -H "Authorization: Bearer $TOKEN" \
               | sed -n 's/.*"image_ref"[: ]*"\([^"]*\)".*/\1/p' || true)"
fi
if [ -n "$IMAGE_REF" ]; then
  echo "  pulling $IMAGE_REF"
  $RUNTIME pull "$IMAGE_REF"
  $RUNTIME tag "$IMAGE_REF" vllm-manager:latest || true
else
  echo "  no image advertised by the admin; building locally (slower, and versions"
  echo "  must match the rest of the cluster — prefer configuring IMAGE_REF)"
  ( cd "$INSTALL_DIR" && bash build.sh )
fi

say "Writing $INSTALL_DIR/.env"
cat > "$INSTALL_DIR/.env" <<EOF
# Generated by join.sh on $(hostname) at $(date -Is)
# The agent auto-detects GPUs, RDMA, NICs and volumes — nothing else is needed here.
CONTAINER_NAME=vllm-worker
USE_SUDO=sudo
READ_ONLY=false
MODELS_DIR=$MODELS_DIR
CANONICAL_MODEL_PATH=/models

CONTROL_PLANE=true
CLUSTER_MODE=false
ROLES=$ROLES
CLUSTER_ID=$CLUSTER_ID
CCP_ADMIN_URL=$(echo "$ADMIN_URL" | sed -e 's#^http://#ws://#' -e 's#^https://#wss://#')
ADMIN_API_KEY=$TOKEN
EOF
chmod 600 "$INSTALL_DIR/.env"
mkdir -p "$MODELS_DIR"

say "Starting the node"
( cd "$INSTALL_DIR" && bash run.sh )

cat <<EOF

Done. This node is joining as: $ROLES
Watch it appear in the admin UI: $ADMIN_URL/cluster

If it does not show up within ~30s:
  $RUNTIME logs vllm-worker
EOF
